### ISSUE TITLE
android端的代码应该如何使用呢?

### ISSUE THREAD

**Issue by ArionHill** [balloonwj/flamingo#11]
如题

**Comment by baloonwj** [comment]
@ArionHill 使用Android Studio打开flamingo安卓版本，编译出apk文件即可，连接的服务器你可以自行部署或者连接我的测试服务器。详情参见： http://blog.csdn.net/analogous_love/article/details/69481542

**Comment by ArionHill** [comment]
用默认的服务器设置为什么注册失败呢?

**Comment by baloonwj** [comment]
@ArionHill 具体问题具体对待，加技术群49114021交流吧。
