### ISSUE TITLE
点击抖动功能，对话框会错乱

### ISSUE THREAD

**Issue by yanzuqing** [balloonwj/flamingo#16]
对方的对话框也会错乱

**Comment by baloonwj** [comment]
@yanzuqing 对话框错乱是什么？截个图吧。

**Comment by baloonwj** [comment]
@yanzuqing 这个应该是你显示器设置问题，和flamingo本身没关系，你换台电脑试试。有些电脑上面就是这样，例如我在虚拟机里面的windows，由于使用的是Windows Basic风格，拖动窗口也会留下痕迹。
