### ISSUE TITLE
chatserver无法运行

### ISSUE THREAD

**Issue by ly1260487269** [balloonwj/flamingo#19]
你好，我这边fileserve和imgserver都正常，就是chatserver无法运行，没有错误提示；
P.S.数据库表是手动建的，版本：CentOS Linux release 7.5.1804 (Core)，gcc version 4.8.5

**Comment by baloonwj** [comment]
@ly1260487269 加下技术交流群578019391贴下故障现象，我给你看下。

**Comment by ly1260487269** [comment]
好的，已申请

**Comment by zx-code123** [comment]
@balloonwj 请问解决了吗？我也遇到了这个问题！

**Comment by zx-code123** [comment]
@ly1260487269 请问你解决了了吗？我也遇到了这个问题！

**Comment by balloonwj** [comment]
@zx-code123 加下技术交流群578019391贴下故障现象，我给你看下。
