### ISSUE TITLE
make的时候报错

### ISSUE THREAD

**Issue by sunmeng1994** [balloonwj/flamingo#23]
up主你好，我用的系统是centos7.4 MySQL用的是8.0，mysql 文件夹在/usr/include下，make报错，请问跟mysql的版本有关吗
![image](https://user-images.githubusercontent.com/12507093/54421398-5670e480-4747-11e9-9102-e9358a823692.png)

**Comment by baloonwj** [comment]
你看下你的mysql相关目录有这个文件吗？可能和版本号有关系，我实际安装的是mysql的开源分支mariadb。
[root@yl-web yl]# yum install mariadb-server mariadb mariadb-devel
参考这里：https://blog.csdn.net/analogous_love/article/details/69481542

**Comment by sunmeng1994** [comment]
> 你看下你的mysql相关目录有这个文件吗？可能和版本号有关系，我实际安装的是mysql的开源分支mariadb。
> [root@yl-web yl]# yum install mariadb-server mariadb mariadb-devel
> 参考这里：https://blog.csdn.net/analogous_love/article/details/69481542

thanks，应该是包含目录层级出了问题，我再找找看

**Comment by self-transcendence** [comment]
/usr/bin/ld: cannot open output file chatserver: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [chatserver] Error 1
make[1]: *** [CMakeFiles/chatserver.dir/all] Error 2
make: *** [all] Error 2
您好，make报错

**Comment by baloonwj** [comment]
> /usr/bin/ld: cannot open output file chatserver: Is a directory
> collect2: error: ld returned 1 exit status
> make[2]: *** [chatserver] Error 1
> make[1]: *** [CMakeFiles/chatserver.dir/all] Error 2
> make: *** [all] Error 2
> 您好，make报错

我没出现这个问题。你加下群578019391，然后at我，我远程给你看下。

**Comment by self-transcendence** [comment]
问题已经被up主解决，原因是三个文件夹冲突，需要删除chatserver 、fileserver 、imgserver 三个文件夹后，make即可

**Comment by baloonwj** [comment]
> 问题已经被up主解决，原因是三个文件夹冲突，需要删除chatserver 、fileserver 、imgserver 三个文件夹后，make即可

后面下载的版本不会再出现这个问题了，我修改了下Windows下的Visual Studio解决方案所在的目录，这样就不会和Linux下生成的二进制文件重名了。感谢您的反馈。
