### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [balloonwj/flamingo#25]
I would like to point out that identifiers like “[`__BUSSINESS_LOGIC_H__`](https://github.com/baloonwj/flamingo/blob/42edf7218912d185d4912451fa6b18efeef54828/flamingoserver/chatserversrc/BussinessLogic.h#L5)” and “[`__MONITOR_SERVER_H__`](https://github.com/baloonwj/flamingo/blob/42edf7218912d185d4912451fa6b18efeef54828/flamingoserver/chatserversrc/MonitorServer.h#L5)” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by balloonwj** [comment]
Then what is the right expected naming convention of the C++ language standard you  @elfring

**Comment by elfring** [comment]
I suggest to [take another look at programming language specifications](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
Would you like to [reduce the tampering with the reserved name space](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description for reserved identifiers")?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
