### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [balloonwj/flamingo#26]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CLVItem](https://github.com/baloonwj/flamingo/blob/4868abb62f783dd8b6b5b891a188f35b5b7b8243/flamingoclient/Source/SkinLib/SkinListCtrl.cpp#L61 "Destructor for CLVItem")
- [CSkinPictureBox::SetBitmap](https://github.com/baloonwj/flamingo/blob/4868abb62f783dd8b6b5b891a188f35b5b7b8243/flamingoclient/Source/SkinLib/SkinPictureBox.cpp#L43 "CSkinPictureBox::SetBitmap function")
- [DEL](https://github.com/baloonwj/flamingo/blob/4868abb62f783dd8b6b5b891a188f35b5b7b8243/flamingoclient/Source/Utils.h#L16 "DEL macro")

**Comment by balloonwj** [comment]
ok，I will do it.

**Comment by elfring** [comment]
:thinking: How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
