### ISSUE TITLE
在检测日志目录的时候，如果目录不存在也会调用closedir，这样没问题嘛？

### ISSUE THREAD

**Issue by Zhu-Pei** [balloonwj/flamingo#3]
实测会设置errno22

**Comment by baloonwj** [comment]
![image](https://user-images.githubusercontent.com/16314187/37500876-c753a602-2906-11e8-8b1b-71d1725e7a9d.png)
您是说这段代码吗？目录不存在会创建目录，closedir是关闭资源句柄。
