### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by sjkang520** [balloonwj/flamingo#31]
Field.cpp里面 m_strValue，m_strFieldName 不都是类的私有变量吗，你这里直接这样写f.m_strValue， f.m_strFieldName是不是有问题。

**Comment by balloonwj** [comment]
C++ 的 private 关键字与其他语言（如 Java）有点区别，其他语言中是只能在自己的成员函数中访问，C++ 是只要在自己的类函数中访问就行：
Field::Field(Field &f)
{
    m_strValue = f.m_strValue;
    m_strFieldName = f.m_strFieldName;

    mType = f.GetType();
}
f.m_strValue 也是在类 Field 类函数中访问的。
不要张嘴就问，自己试一下就知道了，基础不牢，地动山摇。
