### ISSUE TITLE
网络故障

### ISSUE THREAD

**Issue by Jack10001** [balloonwj/flamingo#32]
您好。注册的时候出现网络故障，服务器端的chatserver的端口号不是8888，请问怎么解决？

**Comment by balloonwj** [comment]
chatserver有 3 个端口号，20000 是业务端口号，8888 是监控端口，12345 是 http 端口，你注册应该走的是 20000 端口，看下 README.md，里面有详细的介绍。

**Comment by Jack10001** [comment]
但是当我使用命令   . /chatserver -d    的时候只有一个进程启动，而且还不稳定，有时候自己就关了！
是我 make  的时候出了问题吗？readme我看了好几遍，但是还是不知道什么问题？操作系统是Ubuntu
！麻烦您了！

balloonwj <notifications@github.com> 于2019年6月10日周一 下午5:07写道：

**Comment by balloonwj** [comment]
加 QQ 群：578019391 提问。

**Comment by Jack10001** [comment]
好的，谢谢


balloonwj <notifications@github.com> 于2019年6月10日周一 下午5:13写道：

**Comment by jizhenjin** [comment]
请问   richFace.dll  这个dll 是闭源的吗？
