### ISSUE TITLE
关于  richFace

### ISSUE THREAD

**Issue by jizhenjin** [balloonwj/flamingo#34]
请问 richFace.dll 这个dll 是闭源的吗？

**Comment by L-N521** [comment]
> richFace.dll 这个dll 是闭源的请求吗？

请问在吗，你的仓库中有个项目是法院私有的 叫 court OA  ，请帮我删除一下，因为 网警扫描该项目有漏洞存在代码泄露，感谢了

**Comment by balloonwj** [comment]
@L-N521 我没找到这个仓库，你截个图。如确实存在，我会删除的。

**Comment by L-N521** [comment]
> @L-N521我没找到这个仓库，你截个图。如确实存在，我会删除的。

不好意思，我说的是 jizhenjin这个人，他在您的仓库里评论了，其他方式我实在找不到他，如果可以您能帮我 找到他吗
