### ISSUE TITLE
StringUtil::cut函数有bug

### ISSUE THREAD

**Issue by tjy-cool** [balloonwj/flamingo#37]
StringUtil::cut函数中，给substr2赋值时，应该偏移delimiterlength，而不是1，
源代码
`substr2 = buf.substr(pos + 1);`
应修改为
`substr2 = buf.substr(pos + delimiterlength);`

**Comment by balloonwj** [comment]
@tjy-cool  感谢你的反馈，确实是这样，已经修正。
