### ISSUE TITLE
数据库能注册成功但使用安卓客户端登录一直提示登录失败

### ISSUE THREAD

**Issue by aceip** [balloonwj/flamingo#38]
我用centos8搭了服务环境，编译也都成功，自动生成的数据库。使用安卓客户端能够注册信息，但是使用数据库内的客户信息登录，toast一直提示登录失败，一头雾水。希望看一下。

**Comment by balloonwj** [comment]
通信协议我做了调整，安卓版本的客户端还没做同步更新，pc版是可以的。

**Comment by aceip** [comment]
好的明白了 期待哦☺

**Comment by balloonwj** [comment]
@aceip hello，安卓版本的协议已经更新，现在安卓版本可以正常使用了。如果有问题可以继续反馈哈。
