### ISSUE TITLE
请教一下关于不在同一个局域网下如何通信

### ISSUE THREAD

**Issue by jiujiujiujiujiuaia** [balloonwj/flamingo#4]
我用java也写了一个im 但是如果两台电脑不在一个路由下 就无法通信 请问我应该怎么做 或者这个问题称做什么 我可以自己搜索一下 
谢谢！

**Comment by ender233** [comment]
我理解前提 应该是这个在两个路由下的 IP理论上都是可以访问的.
题主你去看看 baloonwj写的网络排查指导呗，我觉着就可以搞定. 之前碰到网络不通，用nc搞定了.

**Comment by jiujiujiujiujiuaia** [comment]
谢谢谢

**Comment by xxzhaoming** [comment]
nat转发？

**Comment by edidada** [comment]
赞同楼上的说法，内网地址映射，我了解到的socks就是使用类似的技术

**Comment by linkfunlee** [comment]
测试服务 android
客户端 注册失败 有没有测试用户名密码

**Comment by waterfoxfox** [comment]
不在同一局域网下时需要将服务器部署在二者都能访问的网络 比如公网






在 2018-07-18 10:33:59，"linkfunlee" <notifications@github.com> 写道：


测试服务 android
客户端 注册失败 有没有测试用户名密码
