### ISSUE TITLE
flamingo bug反馈页面

### ISSUE THREAD

**Issue by balloonwj** [balloonwj/flamingo#5]
##########flamingo bug反馈页面###################
注意：反馈bug时请说明flamingo的代码来源和终端类型（服务器、pc、还是安卓），并说清楚出现bug的步骤。

**Comment by lemontreehuang** [comment]
PC：好像没有实现自动登陆功能

**Comment by baloonwj** [comment]
> 实现了的。

**Comment by hill121212** [comment]
您好，文件的传输需要经过服务器转发吗？  还是使用 P2P 透传？
