### ISSUE TITLE
windows客户端编译错误

### ISSUE THREAD

**Issue by baichuan51141** [balloonwj/flamingo#59]
无法打开类型库文件: “msxml3.dll”: No such file or directory	Flamingo	C:\Users\PC\Downloads\flamingo-master\flamingo-master\flamingoclient\Source\XmlDocument.h	3	
没有msxml3.dll这个文件

**Comment by balloonwj** [comment]
好奇怪的错误，加微信easy_coder，发下错误截图，看下。
