### ISSUE TITLE
mysqlclient not found

### ISSUE THREAD

**Issue by gchihiha** [balloonwj/flamingo#9]
ubuntu
我已安装mysql-server mysql-client
但还是在cmake步骤提示:
CMake Error at CMakeLists.txt:14 (MESSAGE):
  mysqlclient not found
如何是好?

**Comment by gchihiha** [comment]
apt-get install libmysqlclient-dev
解决.

**Comment by baloonwj** [comment]
很多人会问这个问题，这里统一回复一下：
flamingo使用了mysql，需要依赖mysql开发库，如果是低版本的mysql，需要安装mysql-devel，如果你是mariadb，对应的就是mariadb-devel。
